# Generated by Django 3.0.6 on 2020-05-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activityperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='start_date',
        ),
    ]
