# Generated by Django 3.0.6 on 2020-05-25 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200525_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
