# Generated by Django 3.0.6 on 2020-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200525_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='samp',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
