# Generated by Django 3.0.6 on 2020-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activityperiod_samp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='startDate',
            field=models.DateField(),
        ),
    ]
