# Generated by Django 3.0.6 on 2020-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200525_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='startDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
