# Generated by Django 3.0.6 on 2020-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_activityperiod_samp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='endDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
