# Generated by Django 3.0.6 on 2020-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200526_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
