# Generated by Django 3.0.6 on 2020-05-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200526_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='endDate',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='activityperiod',
            old_name='startDate',
            new_name='star_time',
        ),
    ]
