# Generated by Django 3.0.6 on 2020-05-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200526_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
